const CHANGE_NEW_TODO_TEXT = 'CHANGE_NEW_TODO_TEXT'
const ADD_TODO = 'ADD_TODO'
const TOGGLE_TODO = 'TOGGLE_TODO'
const TOGGLE_ALL_TODOS = 'TOGGLE_ALL_TODOS'
const DESTROY_TODO = 'DESTROY_TODO'
const FILTER_TODO = 'FILTER_TODO'
const CLEAR_COMPLETED_TODOS = 'CLEAR_COMPLETED'

export default {
  CHANGE_NEW_TODO_TEXT,
  ADD_TODO,
  TOGGLE_TODO,
  TOGGLE_ALL_TODOS,
  DESTROY_TODO,
  FILTER_TODO,
  CLEAR_COMPLETED_TODOS,
}
